### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [Infineon/Proximity-Ambient-Light-Sensor#1]
In the file "src/Pals2.cpp", the `Wire.beginTransmission()` before and the `Wire.endTransmission()` after a `Wire.requestFrom()` may be removed.
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 2 and 3.
See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).
It is in the functions `wireReadDataByte()` and `wireReadDataBlock()`.

I suppose the function `wireWriteDataBlock()` should use `Wire.write()` with the data bytes ? That bug is at the moment at line 423.

The functions `getRawProximityOnDemand()` and `getRawAmbientLightOnDemand()` have a `Wire.endTransmission()`. A `Wire.endTransmission()` may not be used on its own. It may not be used to stop or end or clear something, because that is not what that function does.
Those bugs are at the moment at line 109 and 292. Those `Wire.endTransmission()` may be removed.

**Comment by jaenrig-ifx** [comment]
Hi Koepel,
Thank you for your contribution. If you could review the latest changes, we could then close this issue.

**Comment by Koepel** [comment]
It is okay.

When a Master reads for example 4 bytes, then the Master will read 4 bytes regardless how many data bytes the Slave is trying to send. When the Arduino Wire library detects a bus problem, then the data bytes up to that moment might not be reliable. At this moment the Wire.available() can only return zero when there is a problem (it could change in the future).

Therefor I prefer to test if all the bytes are received, and if they are, then read all of them.
In my opinion the [`tle493d::readOut()`](https://github.com/Infineon/TLE493D-3DMagnetic-Sensor/blob/d041a35ed490c1a621ca65446cd1274ce49ed79b/src/util/BusInterface.cpp#L20) and the [`tlv493d::readOut()`](https://github.com/Infineon/TLV493D-A1B6-3DMagnetic-Sensor/blob/4ef868bea65806a820cb880f886f0f0d6cd27f7b/src/util/BusInterface.cpp#L53) do that and are eligant functions.

With that I mind, I noticed these things:
- Why is there a dumpRegister(), when wireReadDataByte() does the same?
- The wireReadDataByte() could have a `if(Wire.available() == 1)` instead of the while-statement.
- In `wireReadDataBlock()`, the 'i' will not get higher than 'len'. I prefer a `if(Wire.available() == len)` and then read all the bytes.

**Comment by jaenrig-ifx** [comment]
Hi Koepel,

Thanks for your valuable review and feedback. We take it into consideration for further improvements. If you find the time and the joy to make this modifications, we will be happy to merge them.

**Comment by mrm023** [comment]
Is there a reason why this doesn´t work with the ESP 32 or the ESP8266?
